// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Musikschule.Models;

#nullable disable

namespace Musikschule.Migrations
{
    [DbContext(typeof(MusikschuleContext))]
    [Migration("20230703080518_create")]
    partial class create
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.19")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Musikschule.Models.Kurs", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("newid()");

                    b.Property<TimeSpan?>("Dauer")
                        .HasColumnType("time");

                    b.Property<string>("Inhalt")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("MusikSchuleId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset?>("Start")
                        .HasColumnType("datetimeoffset");

                    b.Property<int?>("TeilnehmerBelegt")
                        .HasColumnType("int");

                    b.Property<int?>("TeilnehmerGesamt")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("MusikSchuleId");

                    b.ToTable("Kurs", (string)null);
                });

            modelBuilder.Entity("Musikschule.Models.Musikschule", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("newid()");

                    b.Property<string>("Adresse")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Musikschule", (string)null);
                });

            modelBuilder.Entity("Musikschule.Models.Kurs", b =>
                {
                    b.HasOne("Musikschule.Models.Musikschule", "MusikSchule")
                        .WithMany("Kurse")
                        .HasForeignKey("MusikSchuleId");

                    b.Navigation("MusikSchule");
                });

            modelBuilder.Entity("Musikschule.Models.Musikschule", b =>
                {
                    b.Navigation("Kurse");
                });
#pragma warning restore 612, 618
        }
    }
}
